### ISSUE TITLE
Network limits specified in incorrect unit (GB/s -> Gb/s)

### ISSUE THREAD

**Issue by mbowman-skytap** [skytap/well-architected-framework#121]
Text and assets embedded in the following pages present network limits in the incorrect unit (GBps - should be Gbps):

This image on page:
https://skytap.github.io/well-architected-framework/resiliency/
![image](https://user-images.githubusercontent.com/18213683/161118211-cbe04539-a9bf-4a40-b82a-1d330d98670e.png)

Text on pages:
* https://skytap.github.io/well-architected-framework/resiliency/designconsiderationsazure/
* https://skytap.github.io/well-architected-framework/resiliency/designconsiderationsibm/

**Comment by matthewromeroskytap** [comment]
I've updated the text in the pages - the images will take more time - the text will update EOM with the larger update, you can review in the March2022-Updates branch.

**Comment by mbowman-skytap** [comment]
Looks like the images on the resiliency base page have been removed, but the incorrect values/unit labels remain in the designconsiderations docs, even in April2022-Updates branch.

I've corrected the limit values/unit labels in a fork and submitted PR #135 to merge the updates into master. Please review and merge if the change is acceptable to you!

**Comment by mbowman-skytap** [comment]
And looks like PR #135 has been merged (fast like lightning!) - thank you Matt!
