### ISSUE TITLE
Broken Links - Jast 404 Review Item 22

### ISSUE THREAD

**Issue by matthewromeroskytap** [skytap/well-architected-framework#212]
Following the JAST 404 audit, @jm-carolinah identified links in the page: [https://skytap.github.io/well-architected-framework/security/](https://skytap.github.io/well-architected-framework/security/) had errors. - **NOTE: Including NAVTREE header.** 

Verify the updated links @jm-carolinah has in the Audit doc are in the committed branch pre-merge as part of the Merge to master review cycle. 

[Skytap git.io broken links review.pdf](https://github.com/skytap/well-architected-framework/files/10844432/Skytap.git.io.broken.links.review.pdf)

**Comment by Matt2021-A** [comment]
Confirmed updates to [security/README.md](https://github.com/skytap/well-architected-framework/pull/190/files#diff-af4558684ed2efe44f6561782ca52ab0ac9c8511335eb5d6cd17700287ac5692)
