### ISSUE TITLE
Broken Links - Jast 404 Review Item 23

### ISSUE THREAD

**Issue by matthewromeroskytap** [skytap/well-architected-framework#213]
Following the JAST 404 audit, @jm-carolinah identified links in the page: [https://skytap.github.io/well-architected-framework/security/virtual-machines](https://skytap.github.io/well-architected-framework/security/virtual-machines) had errors.

Verify the updated links @jm-carolinah has in the Audit doc are in the committed branch pre-merge as part of the Merge to master review cycle.

@Matt2021-A  to add and update the missing external links that she identified. 

[Skytap git.io broken links review.pdf](https://github.com/skytap/well-architected-framework/files/10844432/Skytap.git.io.broken.links.review.pdf)

**Comment by Matt2021-A** [comment]
Confirmed updates to [security/virtualmachines.md](https://github.com/skytap/well-architected-framework/pull/190/files#diff-dbfea1a86b8ebcd3e2d6d54b1ec82fc5daabf312cc6fefc3982d755a78354436) - but will wait to close this until the next pull request - as @Matt2021-A  still needs to add the updated external links.

**Comment by matthewromeroskytap** [comment]
The bad link is: 
https://www.ibm.com/support/pages/configuring-ssl-telnet-and-host-servers-server-authentication-first-time
Updated Links: 
https://www.ibm.com/support/pages/configuring-telnet-and-host-servers-server-authentication-tls-first-time
https://www.ibm.com/support/pages/configuring-ibm-i-access-windows-ssl-use-client-authentication

Applied to [security/virtualmachines.md](https://github.com/skytap/well-architected-framework/pull/190/files#diff-dbfea1a86b8ebcd3e2d6d54b1ec82fc5daabf312cc6fefc3982d755a78354436)

Fixed in PR: https://github.com/skytap/well-architected-framework/pull/216
