### ISSUE TITLE
Update Skytap HA Overview section permalink

### ISSUE THREAD

**Issue by matthewromeroskytap** [skytap/well-architected-framework#214]
Currently the page: resiliency/hadr.md
has the following permalink: /resiliency/ibmi-disaster-recovery/ - would like to update this to /resiliency/high-availability/

**Comment by matthewromeroskytap** [comment]
Thanks @jm-carolinah for getting on this one so quickly - can you let me know what your eta is on #191

**Comment by jm-carolinah** [comment]
> Thanks @jm-carolinah for getting on this one so quickly - can you let me know what your eta is on #191

I can get on it tomorrow morning!
