### ISSUE TITLE
New Page - DSI Configuration of iSCSI VTL Backups

### ISSUE THREAD

**Issue by matthewromeroskytap** [skytap/well-architected-framework#223]
This project is tracked under the Asana task: https://app.asana.com/0/1201296971804549/1203759921503544/f

**Comment by matthewromeroskytap** [comment]
Will Close when final version merges to master

**Comment by Matt2021-A** [comment]
@kimcladitis / @jm-carolinah - re-opening this issue, as the page didn't deploy in GitHub Actions - https://github.com/skytap/well-architected-framework/actions/runs/4319271218 - I recommend re-running the action, and if it fails again to validate that the resiliency/solutions/VTL/DSI-iSCSI-VTL-Backups.md file is UTF-8.

**Comment by Matt2021-A** [comment]
this is attached to PR: #228
